apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ./pacman-namespace.yaml
- ./pacman-deployment.yaml
- ./pacman-service.yaml
- ./pacman-route.yaml
images:
- name: quay.io/rhdevelopers/pacman-kikd
  newTag: 1.0.0
