apiVersion: tekton.dev/v1beta1
kind: TaskRun
metadata:
 name: build-app-run-pacman
spec:
 serviceAccountName: build-bot
 params:
   - name: dockerio-credentials-secret
     value: dockerio-credentials
   - name: container-image
     value: lordofthejars/pacman-kikd:1.0.1
 resources:
   inputs:
     - name: source
       resourceRef:
         name: git-source
 taskRef:
   name: build-app-pacman